[package]
name = "eskf"
version = "0.1.0"
authors = ["Jørgen Nordmoen <jorgen@nordmoen.net>"]
edition = "2018"

[features]
default = ["std", "full-reset"]

# Perform a full filter reset during measurement update
full-reset = []
# A more stable covariance update, but more computationally expensive
cov-symmetric = []
# Stable, symmetric and positive covariance update, computationally expensive
cov-joseph = []
# Use Rust 'std', disable to enable 'no_std'
std = ["nalgebra/std"]

[dependencies]
nalgebra = "0.25"

[dev-dependencies]
approx = "0.4.0"
nalgebra = {version = "0.25", features = ["serde-serialize"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
plotly = "0.6.0"
